### PR TITLE
#20: Fix deserializing timestamp mapping

### LINKED ISSUE #20: Deserializing ToTimestampMapping always sets useTimestampWithLocalTimezoneType to true
When deserializing a ToTimestampMapping from JSON, class `ToTimestampMappingDeserializer` always uses the default value (true) for property useTimestampWithLocalTimezoneType.

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #20

### CODE REVIEW

File: src/test/java/com/exasol/adapter/document/edml/deserializer/EdmlDeserializerTest.java [hunk 1]
```diff
@@ -106,10 +109,15 @@ void testDeserializeToTableMapping() {
...
-                .useTimestampWithLocalTimezoneType(true).build();
+    @CsvSource({ "NULL, true", //
+            "CONVERT_OR_ABORT, true", //
+            "NULL, false", //
+            "CONVERT_OR_ABORT, false", })
+    @ParameterizedTest
+    void testDeserializeToTimestampMapping(final ConvertableMappingErrorBehaviour behaviour,
+            final boolean localTimezone) {
+        final var mapping = ToTimestampMapping.builder().notTimestampBehavior(behaviour)
+                .useTimestampWithLocalTimezoneType(localTimezone).build();
```
Comment (redcatbear) [inline src/test/java/com/exasol/adapter/document/edml/deserializer/EdmlDeserializerTest.java]:
```suggestion
            final boolean uselocalTimezone) {
        final var mapping = ToTimestampMapping.builder().notTimestampBehavior(behaviour)
                .useTimestampWithLocalTimezoneType(uselocalTimezone).build();
```

**Review by redcatbear — DISMISSED** [review]

**Review by ckunki — APPROVED** [review]
